# this script is for sketching the node engine logic


# this would be done in the game engine

from classes.game.node_context import NodeContext
from classes.entities.employee import Employee
from classes.data.button_dat import ButtonDat

button_dat = ButtonDat()

# aha so I can refactor this to be generated by the context?
employee = Employee(button_dat.employee_df.iloc[0]['job_title'],
                    button_dat.employee_df.iloc[0]['department'])

context = NodeContext(employee=employee)


# node engine logic
from classes.text_gen.textgen_employee import EmployeeTextGenerator

# todo node title

employee.set_current_titles()

employee_text_gen = EmployeeTextGenerator()
print(employee_text_gen.generate_text(context))
